table(X2023_sTB_survey$Gender)
ECN <-table(X2023_STB_survey$Gender)prop.table
(ECN)table(X2023_sTB_survey$Gen,X2023_STB_survey $Grade)
barplot(table(X2023_STB_survey$Nationality))
barplot(table(X2023_STB_survey$residentialarea))
barplot(table(X2023_STB_survey$Gender,X2023_STB_survey$Grade))
pie(table(X2023_STB_surveysGrade))
barplot(table(X2023_STB_survey$Age))
entry<-able(X2023_STB_survey$Grade,X2023_STB_survey $Age)
barp1ot(entry,legend = TRUE)
boxplot(X2023_STB_surveys$`Grade`,X2023_STB_surveys'Age',main="Grade and age”,col=”pink”,names=c(“grade”,”age”))
Plot(X=X2023_STB_surveys$`Grade`,y=X2023_STB_surveys`Age`,xlab=”Grade”,ylab=”Age”,main=”Grade and Age”)
